#! /bin/sh

#快捷键
pgrep -x sxhkd > /dev/null || sxhkd &

#nitrogen
nitrogen --random --set-zoom-fill &

#picom
picom &

#polybar example  &
bash  $HOME/.config/polybar/launch.sh --cuts &

#mpd
mpd &

#蓝牙






fcitx-autostart &
#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d  1 2 3 4 5 6 7 8 9 0
#bspc monitor -d HDMI-1  6 7 8 9 0 

bspc config border_width         4
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp-2.10 desktop='^5' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#我自己的配置
bspc rule -a Typora desktop='^4' state=floating follow=on

